# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseDemo' do

  pod 'AFNetworking', '~> 3.0'
  pod 'MJExtension', '~> 3.0.15.1'

  target 'BaseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
